defaults:
  - _self_

manifold_kwargs:
  P: 2000
  N: 30
  M: 200
  num_classes: 1
  m_tr: 1
  centroid_seed: 510

exp_kwargs:
  lamb: 1e-7
  num_trials: 10
  grid_size: 3
  fn_list: [linsvr2]
  suffix: _trial_grid_size_${exp_kwargs.grid_size}
  file_name: local_experiment_toy_data_P_${manifold_kwargs.P}_N_${manifold_kwargs.N}_lamb_${exp_kwargs.lamb}_trials_${exp_kwargs.num_trials}_grid_size_${exp_kwargs.grid_size}_seed_${manifold_kwargs.centroid_seed}.npz

experiment_name: ${now:%Y-%m-%d_%H-%M-%S}